version: "3"
services:
  auth:
    container_name: "AuthService"
    image: rpc:1.0
    ports:
      - "${SERVER_AUTH_PORT}:${SERVER_AUTH_PORT}"
    env_file:
      - .env
    command:
      - ./build/auth
  comment:
    container_name: "CommentService"
    image: rpc:1.0
    ports:
      - "${SERVER_COMMENT_PORT}:${SERVER_COMMENT_PORT}"
    env_file:
      - .env
    command:
      - ./build/comment
  favorite:
    container_name: "FavoriteService"
    image: rpc:1.0
    ports:
      - "${SERVER_FAVORITE_PORT}:${SERVER_FAVORITE_PORT}"
    env_file:
      - .env
    command:
      - ./build/favorite
  user:
    container_name: "UserService"
    image: rpc:1.0
    ports:
      - "${SERVER_USER_PORT}:${SERVER_USER_PORT}"
    env_file:
      - .env
    command:
      - ./build/user
  video:
    container_name: "VideoService"
    image: rpc:1.0
    ports:
      - "${SERVER_VIDEO_PORT}:${SERVER_VIDEO_PORT}"
    env_file:
      - .env
    volumes:
      - C:\Users\67561\GolandProjects\rpc-douyin\feed:/feed
    command:
      - ./build/video
  web:
    container_name: "WebService"
    image: rpc:1.0
    depends_on:
      - auth
      - comment
      - favorite
      - user
      - video
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - C:\Users\67561\GolandProjects\rpc-douyin\feed:/feed
    command:
      - ./build/web