database:
  name: "douyin"
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
etcd:
  host: "127.0.0.1"
  port: 2379
kafka:
  host: "127.0.0.1"
  port: 9092
server:
  host: "127.0.0.1"
  port: 8080
  user:
    name: "UserService"
    host: "127.0.0.1"
    port: 8000
  auth:
    name: "AuthService"
    host: "127.0.0.1"
    port: 8001
  video:
    name: "VideoService"
    host: "127.0.0.1"
    port: 8002
  favorite:
    name: "favoriteService"
    host: "127.0.0.1"
    port: 8003
  comment:
    name: "commentService"
    host: "127.0.0.1"
    port: 8004
file:
  dir: "feed"
  max: 10485760